### ISSUE TITLE
Tests fail one at a time

### ISSUE THREAD

**Issue by robertmackenzie** [BSkyB/cezanne#2]
At the moment, if you run a series of browser tests, when the first one fails, execution of the test suite is aborted. Say you are creating a set of new screenshots for a test you've just added. You must either re-run the tests once for each browser and approve, or manually copy screenshots in via dropbox.

It would be more useful if the whole suite was run and all errors reported at the end. So in the example above, you could go through the approval app and approve all the new screenshots in one go.

**Comment by pigats** [comment]
it probably depends on how you loop through the browsers you want to test against. as we agreed, I'm closing this
