### ISSUE TITLE
Screenshots are failing when screenshots look identical

### ISSUE THREAD

**Issue by skyhaikuteam** [BSkyB/cezanne#7]
When no visible changes can be seen screenshots are failing

**Comment by pigats** [comment]
the threshold we are using for PSNR image comparison might be too high, and so the test would fail even if the naked eye can not spot differences between the reference and the test screenshots. Starting from version 0.1.0 you can now pass in your own threshold value in the config block 

```
Cezanne.configure do |config|
  config.similarity_threshold = 42 (default for PSNR)
end
```

Have a look at http://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio to understand what this threshold means :)
